name: ChestShop
main: ChestShop\ChestShop
version: 3.0.0
api: [1.13.1, 2.0.0]
author: "MinecrafterJPN & LostTeam"
description: "Create Your own shop in a chest!"
softdepend:
 - PocketMoney
 - EconomyAPI
commands:
  id:
    usage: "Usage: /id <Item Name>"
    description: "Search item ID"
    permission: id.cmd
permissions:
  id.cmd:
    default: true
  chestshop.make:
    default: op
    children:
     chestshop.make.3:
      default: true
     chestshop.make.unlimited:
      default: op